### PR TITLE
Changes to documentation 

### PR DESCRIPTION
**Pull request by adam-coates**
My last pull request I forgot to add and example of running the `:Zselectannotations` command in the doc. 

Not sure if the `README.md` on the github page could also showcase this. But in the interest of keeping the readme uniform, I'd refrain from making a pull request to avoid differences in colorscheme/ example references in the gifs in the readme.

### CODE REVIEW

**Comment by jalvesaq** [comment]
It's OK to have differences in style (colorscheme, etc). I see this as good (diversity in appearance over standardization).

**Comment by adam-coates** [comment]
Okay then perhaps I can also update the readme as well.

**Comment by adam-coates** [comment]
Okay I'm happy to do this, it's on todo list.

**Comment by adam-coates** [comment]
So I updated the README, and I added back the `lua` into the `doc`. I was unsure about the other code blocks though. Let me know what you think.

**Comment by adam-coates** [comment]
You're welcome thanks!

**Comment by jalvesaq** [comment]
I added the language tags that were missing to the code blocks.

**Comment by adam-coates** [comment]
Great thanks for doing that!

**Pull request merged**
